### ISSUE TITLE
Support pytest 7

### ISSUE THREAD

**Issue by whazor** [dazza-codes/pytest-aiomoto#18]
When installing pytest-aiomoto: `pytest-aiomoto 0.4.0 depends on pytest<7.0.0 and >=6.2.5`

**Comment by dazza-codes** [comment]
Thanks for submitting this request.  To date, this project is only tested with pytest 6.x.  The pytest 7.x release is a recent major version release that could break things in this current project.  If I don't look into this soon, please submit a PR on this repo with an update to pytest 7.x in the `pyproject.toml` specs, and other updates for any pytest plugins that also work with 7.x.

To further evaluate an update to pytest 7.x, I would also need to use a pre-release of this package in the [aio-aws](https://github.com/dazza-codes/aio-aws) project.  Doing that would provide some data points about the downstream impact of updating pytest to 7.x.

**Comment by dazza-codes** [comment]
```
$ make package-publish 
All set!
Building pytest-aiomoto (0.5.0)
  - Building sdist
  - Built pytest-aiomoto-0.5.0.tar.gz
  - Building wheel
  - Built pytest_aiomoto-0.5.0-py3-none-any.whl
Checking dist/pytest_aiomoto-0.5.0-py3-none-any.whl: PASSED
Checking dist/pytest-aiomoto-0.5.0.tar.gz: PASSED

Publishing pytest-aiomoto (0.5.0) to PyPI
 - Uploading pytest-aiomoto-0.5.0.tar.gz 100%
 - Uploading pytest_aiomoto-0.5.0-py3-none-any.whl 100%

```

**Comment by dazza-codes** [comment]
Examples of upgrading to 0.5.x can be found in https://github.com/dazza-codes/aio-aws/pull/89
- e.g. the `aio*server` fixtures return the service object, not use the endpoint URL
